routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RolleController;
use App\Http\Controllers\ActionController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\SystemController;
use App\Http\Controllers\PermisiController;
use App\Http\Controllers\PermisionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//home
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->middleware(['auth'])->name('home');



Route::middleware(['auth', 'role:admin'])->name('admin.')->group(function () {
//module
Route::resource('module',ModuleController::class);

//sistem
Route::resource('system',SystemController::class);

//action
Route::resource('action',ActionController::class);

//permision
Route::resource('permision',PermisionController::class);



Route::resource('rolle',RolleController::class);


// Route::post('/roles/{role}/permissions', [RolleController::class, 'givePermission'])->name('roles.permissions');
// Route::delete('/roles/{role}/permissions/{permission}', [RolleController::class, 'revokePermission'])->name('roles.permissions.revoke');

Route::post('/rolle/{id}/edit', [RolleController::class, 'givePermission']);
Route::delete('/roles/{role}/permissions/{permission}', [RolleController::class, 'revokePermission'])->name('roles.permissions.revoke');




Route::get('/user', [UserController::class, 'index'])->name('users.index');
Route::get('/user/{id}/show', [UserController::class, 'show'])->name('users.show');
Route::delete('/user/{id}', [UserController::class, 'destroy'])->name('users.destroy');

Route::post('/user/{id}/ya', [UserController::class, 'assignRole'])->name('users.roles');
Route::delete('/users/{user}/roles/{role}', [UserController::class, 'removeRole'])->name('users.roles.remove');

Route::post('/user/{id}/show', [UserController::class, 'givePermission'])->name('users.permissions');
Route::delete('/users/{user}/permissions/{permission}', [UserController::class, 'revokePermission'])->name('users.permissions.revoke');

Route::get('/user/create', [UserController::class, 'create'])->name('users.create');
Route::post('/user/create', [UserController::class, 'store'])->name('users.store');
});

app/Http/Controllers/RolleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;
use Spatie\Permission\Models\Permission;


class RolleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     public function __construct()
     {
         $this->middleware('permission:rolle index', ['only' => ['index']]);
         $this->middleware('permission:create rolle', ['only' => ['create', 'store']]);
         $this->middleware('permission:edit rolle', ['only' => ['edit', 'update']]);
         $this->middleware('permission:delete rolle', ['only' => ['destroy']]);
         $this->middleware('permission:create permision in rolle', ['only' => ['givePermission']]);
         $this->middleware('permission:delete permision in rolle', ['only' => ['revokePermission']]);
     }

    public function index()
    {
       // $roles = Role::whereNotIn('name', ['admin'])->get();
       $roles = Role::orderBy('id', 'desc')->get();
       return view('rolle.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('rolle.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate(['name' => ['required', 'min:3']]);
        Role::create($validated);
        return redirect('/rolle')->with('success', 'Successfully input data');
        // return to_route('rolleindex')->with('message', 'Role Created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit( $id)
    {
        $permissions = Permission::all();
         $role = Role::where('id', $id)->first();
      return view('rolle/edit',compact('role','permissions'));


    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,  $id)
    {
        
        Session::flash('name', $request->name);

        $request->validate([
            'name' => 'required',
        ]);

        $data = [
            'name' => $request->input('name'),
           
        ];

        Role::where('id', $id)->update($data);
        return redirect('/rolle')->with('success', 'Successfully update data');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // $role->delete();
        // return back()->with('message', 'Role deleted.');
        Role::where('id', $id)->delete();
        return redirect('/rolle')->with('success', 'Delete data successfully');
    }


    public function givePermission(Request $request,  $id)
    {
                        $role = Role::where('id', $id)->firstOrFail();
                        $permission = Permission::where('id',$request->permision_name)->firstOrFail();   
                $role->givePermissionTo($permission);
                return back();

    }

    public function revokePermission(Role $role, Permission $permission)
    {
        if($role->hasPermissionTo($permission)){
            $role->revokePermissionTo($permission);
            return back()->with('success', 'Permission revoked.');
        }
        return back()->with('success', 'Permission not exists.');
    }
}

resources/views/rolle/create.blade.php
@extends('template.admin')
@section('name')
    

<form method="post" action="/rolle" >
    
    @include('pesan.pesan')
    @csrf
    <div class="my-3 p-3 bg-body rounded shadow-sm">
        <a href='{{url('rolle')}}' class="btn btn-outline-success"><i class="bi bi-skip-backward-btn-fill"></i></a>

        <div class="mb-3 row">
            <label for="name" class="col-sm-2 col-form-label"> Role name </label>
            <div class="col-sm-10">
              <input type="text" id="name" name="name" class="form-control" />
            </div>
    

    <div class="mb-3 row">
        <label for="tahun" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10"><button type="submit" class="btn btn-outline-primary" name="submit"><i class="bi bi-save"></i></button></div>
    </div>
</div>

</form>

@endsection

resources/views/rolle/edit.blade.php
@extends('template.admin')
@section('name')

                  <form action='{{ url('rolle/'.$role->id) }}'  method='post' >
                        @include('pesan.pesan')
                        <a href='{{url('rolle')}}' class="btn btn-outline-success"><i class="bi bi-skip-backward-btn-fill"></i></a>
                        @csrf
                        @method('PUT')
                        <div class="my-3 p-3 bg-body rounded shadow-sm">
                            <div class="mb-3 row">
                                <label for="name" class="col-sm-2 col-form-label">name</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name='name' value="{{$role->name}}" id="name">
                                </div>
                            </div>
                            <div class="mb-3 row">
                                <label for="tahun" class="col-sm-2 col-form-label"></label>
                                <div class="col-sm-10"><button type="submit" class="btn btn-primary" name="submit">save</button></div>
                            </div>
                        </div>
                    </form>
            

                    @can('create permision')
                   <form method="POST" action="{{ url('rolle/'.$role->id.'/edit') }}">
                            @csrf
                            <div class="my-3 p-3 bg-body rounded shadow-sm">
                                <div class="mb-3 row">
                                    <label for="permision_name" class="col-sm-2 col-form-label">permision_name</label>
                                    <div class="col-sm-10">
                                        <select type="text" name="permision_name"  name="permision_name"  value="{{Session::get('permision_name')}}" id="permision_name"  class="form-control">
                                                    @foreach ($permissions as $item)
                                                <option value="{{ $item->id }}"> {{ $item->name }}</option>
                                                         @endforeach
                                          </select>
                                    </div>
                                    </div>
                                    <div class="mb-3 row">
                                        <label for="tahun" class="col-sm-2 col-form-label"></label>
                                        <div class="col-sm-10"><button type="submit" class="btn btn-primary" name="submit">assign</button></div>
                                    </div>
                                </form>
                        </div> 
                            @endcan


                            @can('delete permision')
                <div class="mt-6 p-2 bg-slate-100">
                            <h5 class="text-2xl font-semibold">Role Permissions</h5>
                            <div class="flex space-x-2 mt-4 p-2">
                                @if ($role->permissions)
                                    @foreach ($role->permissions as $role_permission)
                                        <form class="px-4 py-2 bg-red-500 hover:bg-red-700 text-white rounded-md" method="POST"
                                            action="{{ route('admin.roles.permissions.revoke', [$role->id, $role_permission->id]) }}"
                                            onsubmit="return confirm('Are you sure?');">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit">{{ $role_permission->name }}</button>
                                        </form>
                                    @endforeach
                                @endif
                            </div>
                        @endcan
                
                    </div>
        

          


@endsection

resources/views/rolle/index.blade.php
  

@extends('template.admin')
@section('name')  

                    @include('pesan.pesan')

                  
   <!-- START data -->
        <div class="my-3 p-3 bg-body rounded shadow-sm">
                <!-- TOMBOL TAMBAH data -->
                @can('create rolle')
                <div class="pb-3">
                  <a href='/rolle/create' class="btn btn-primary"> add</a>
               </div> 
               @endcan
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th class="col-md-1">rolle</th>
                            <th class="col-md-2">action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($roles as $role)
                      
                        <tr>
                            <td>{{ $role->name }}</td>
                         
                            <td>
                                @can('edit rolle')
                                <a href= '{{url('rolle/'.$role->id.'/edit')}}'  class="btn btn-warning btn-sm"><i class="bi bi-pen"></i></a>
                                @endcan
                                @can('delete rolle')
                                <form onsubmit="return confirm('Yakin mau menghapus data?')" class='d-inline' action="{{ url('rolle/'.$role->id) }}" method="post">
                                    @csrf 
                                    @method('DELETE')
                                    <button type="submit" name="submit" class="btn btn-danger btn-sm"><i class="bi bi-trash"></i></button>
                                </form>
                            @endcan
                            </td>
                        </tr>
                            
                        @endforeach
                    </tbody>
                </table>
          </div> 
          @endsection