routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RolleController;
use App\Http\Controllers\ActionController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\SystemController;
use App\Http\Controllers\PermisiController;
use App\Http\Controllers\PermisionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//home
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->middleware(['auth'])->name('home');



Route::middleware(['auth', 'role:admin'])->name('admin.')->group(function () {
//module
Route::resource('module',ModuleController::class);

//sistem
Route::resource('system',SystemController::class);

//action
Route::resource('action',ActionController::class);

//permision
Route::resource('permision',PermisionController::class);



Route::resource('rolle',RolleController::class);


// Route::post('/roles/{role}/permissions', [RolleController::class, 'givePermission'])->name('roles.permissions');
// Route::delete('/roles/{role}/permissions/{permission}', [RolleController::class, 'revokePermission'])->name('roles.permissions.revoke');

Route::post('/rolle/{id}/edit', [RolleController::class, 'givePermission']);
Route::delete('/roles/{role}/permissions/{permission}', [RolleController::class, 'revokePermission'])->name('roles.permissions.revoke');




Route::get('/user', [UserController::class, 'index'])->name('users.index');
Route::get('/user/{id}/show', [UserController::class, 'show'])->name('users.show');
Route::delete('/user/{id}', [UserController::class, 'destroy'])->name('users.destroy');

Route::post('/user/{id}/ya', [UserController::class, 'assignRole'])->name('users.roles');
Route::delete('/users/{user}/roles/{role}', [UserController::class, 'removeRole'])->name('users.roles.remove');

Route::post('/user/{id}/show', [UserController::class, 'givePermission'])->name('users.permissions');
Route::delete('/users/{user}/permissions/{permission}', [UserController::class, 'revokePermission'])->name('users.permissions.revoke');

Route::get('/user/create', [UserController::class, 'create'])->name('users.create');
Route::post('/user/create', [UserController::class, 'store'])->name('users.store');
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;
    // use HasRoles;
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use App\Models\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;
use Spatie\Permission\Models\Permission;

class UserController extends Controller
{

    public function index()
    {
        $users = User::all();

        return view('user.index', compact('users'));
    }

    public function show($id)
    {
        $rolle = Role::all();
        $permissions = Permission::all();
        $user = User::where('id', $id)->first();
      return view('user.rolle',compact('rolle','user','permissions'));
    }

    public function assignRole(Request $request,  $id)
    {
        $user = User::where('id', $id)->firstOrFail();
        $rolle = Role::where('id',$request->rolle)->firstOrFail();
        $user->assignRole($rolle);
        return back();
    }

    public function removeRole(User $user, Role $role)
    {
        if ($user->hasRole($role)) {
            $user->removeRole($role);
            return back()->with('success', 'Role removed.');
        }

        return back()->with('success', 'Role not exists.');
    }



    public function givePermission(Request $request,  $id)
    {
                         $user = User::where('id', $id)->firstOrFail();
                        $permission = Permission::where('id',$request->permision_name)->firstOrFail();   
                $user->givePermissionTo($permission);
                return back();

    }

    public function revokePermission(User $user, Permission $permission)
    {
        if($user->hasPermissionTo($permission)){
            $user->revokePermissionTo($permission);
            return back()->with('success', 'Permission revoked.');
        }
        return back()->with('success', 'Permission not exists.');
    }





    public function create()
    {
        return view('user.create');
    }

    public function store(Request $request)
    {
        Session::flash('name', $request->name);
        Session::flash('email', $request->email);
        Session::flash('password', $request->password);

        $request->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6',
        ]);



        $user = [
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password)
        ];


        User::create($user);
        return redirect()->to('user')->with('success', 'succes add');

    }
}

resources/views/user/create.blade.php
@extends('template.admin')
@section('name')

<form action='{{ url('/user/create') }}'  method='post'>

    @csrf
    <div class="my-3 p-3 bg-body rounded shadow-sm">
        <a href='{{url('user')}}' class="btn btn-outline-success"><i class="bi bi-skip-backward-btn-fill"></i></a>
        @include('pesan.pesan')
        <div class="mb-3 row">
            <label for="name" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name='name' value="{{Session::get('name')}}" id="name">
            </div>
        </div>
        <div class="mb-3 row">
            <label for="email" class="col-sm-2 col-form-label">email</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name='email' value="{{Session::get('email')}}" id="email">
            </div>
        </div>

        <div class="mb-3 row">
         <label for="password" class="col-sm-2 col-form-label">Password</label>
         <div class="col-sm-10">
                <input type="password"  class="form-control"name="password"id="password">
            </div>
        </div>
        <div class="mb-3 row">
            <label for="tahun" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10"><button type="submit" class="btn btn-primary" name="submit"><i class="bi bi-save"></i></button></div>
        </div>

    </div>

</form>

@endsection

resources/views/user/index.blade.php
@extends('template.admin')
@section('name')  

                    @include('pesan.pesan')    
   <!-- START data -->
        <div class="my-3 p-3 bg-body rounded shadow-sm">
                <!-- TOMBOL TAMBAH data -->
                <div class="pb-3">
                  <a href='/user/create' class="btn btn-primary"> add</a>
               </div> 
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th class="col-md-1">rolle</th>
                            <th class="col-md-2">action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $user)
                      
                        <tr>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>
                                <a href= '{{url('user/'.$user->id.'/show')}}'  class="btn btn-warning btn-sm"><i class="bi bi-pen"></i></a>
                                <form onsubmit="return confirm('Yakin mau menghapus data?')" class='d-inline' action="{{ url('user/'.$user->id) }}" method="post">
                                    @csrf 
                                    @method('DELETE')
                                    <button type="submit" name="submit" class="btn btn-danger btn-sm"><i class="bi bi-trash"></i></button>
                                </form>
                            </td>
                        </tr>
                            
                        @endforeach
                    </tbody>
                </table>
          </div> 
     
@endsection

resources/views/user/rolle.blade.php
@extends('template.admin')
@section('name')

                  <form action='{{ url('user/'.$user->id) }}'  method='post' >
                        @include('pesan.pesan')
                        <a href='{{url('user')}}' class="btn btn-outline-success"><i class="bi bi-skip-backward-btn-fill"></i></a>
                        <div class="my-3 p-3 bg-body rounded shadow-sm">
                            <div class="mb-3 row">
                                <label for="name" class="col-sm-2 col-form-label">name</label>
                                <div class="col-sm-10">
                                    {{ $user->name }}
                                </div>
                            </div>
                            </div>
                            <div class="my-3 p-3 bg-body rounded shadow-sm">
                                <div class="mb-3 row">
                                    <label for="name" class="col-sm-2 col-form-label">email</label>
                                    <div class="col-sm-10">
                                        {{ $user->email }}
                                    </div>
                                   
                                </div>
                        </div>
                    </form>
            
                   <form method="POST" action="{{ url('user/'.$user->id.'/ya') }}">
                            @csrf
                            <div class="my-3 p-3 bg-body rounded shadow-sm">
                                <div class="mb-3 row">
                                    <label for="rolle" class="col-sm-2 col-form-label">role name</label>
                                    <div class="col-sm-10">
                                        <select type="text" name="rolle"  name="rolle"  value="{{Session::get('rolle')}}" id="rolle"  class="form-control">
                                                    @foreach ($rolle as $item)
                                                <option value="{{ $item->id }}"> {{ $item->name }}</option>
                                                      @endforeach
                                          </select>
                                    </div>
                                    </div>
                                    <div class="mb-3 row">
                                        <label for="tahun" class="col-sm-2 col-form-label"></label>
                                        <div class="col-sm-10"><button type="submit" class="btn btn-primary" name="submit">assign</button></div>
                                    </div>
                                </form>
                     


                        <div class="mt-6 p-2 bg-slate-100">
                            <h2 class="text-2xl font-semibold">Roles</h2>
                            <div class="flex space-x-2 mt-4 p-2">
                                @if ($user->roles)
                                    @foreach ($user->roles as $user_role)
                                        <form class="px-4 py-2 bg-red-500 hover:bg-red-700 text-white rounded-md" method="POST"
                                            action="{{ route('admin.users.roles.remove', [$user->id, $user_role->id]) }}"
                                            onsubmit="return confirm('Are you sure?');">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit">{{ $user_role->name }}</button>
                                        </form>
                                    @endforeach
                                @endif
                            </div>

                
                    </div>
        

          
                    <form method="POST" action="{{ url('user/'.$user->id.'/show') }}">
                        @csrf
                        <div class="my-3 p-3 bg-body rounded shadow-sm">
                            <div class="mb-3 row">
                                <label for="permision_name" class="col-sm-2 col-form-label">permision_name</label>
                                <div class="col-sm-10">
                                    <select type="text" name="permision_name"  name="permision_name"  value="{{Session::get('permision_name')}}" id="permision_name"  class="form-control">
                                                @foreach ($permissions as $item)
                                            <option value="{{ $item->id }}"> {{ $item->name }}</option>
                                                     @endforeach
                                      </select>
                                </div>
                                </div>
                                <div class="mb-3 row">
                                    <label for="tahun" class="col-sm-2 col-form-label"></label>
                                    <div class="col-sm-10"><button type="submit" class="btn btn-primary" name="submit">assign</button></div>
                                </div>
                            </form>
                    


            <div class="mt-6 p-2 bg-slate-100">
                        <h5 class="text-2xl font-semibold">User Permissions</h5>
                        <div class="flex space-x-2 mt-4 p-2">
                            @if ($user->permissions)
                                @foreach ($user->permissions as $user_permission)
                                    <form class="px-4 py-2 bg-red-500 hover:bg-red-700 text-white rounded-md" method="POST"
                                        action="{{ route('admin.users.permissions.revoke', [$user->id, $user_permission->id]) }}"
                                        onsubmit="return confirm('Are you sure?');">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit">{{ $user_permission->name }}</button>
                                    </form>
                                @endforeach
                            @endif
                        </div>
                </div>


               
@endsection